### ISSUE TITLE
How are the movie_embedding and item_embedding generated?

### ISSUE THREAD

**Issue by zcfinal** [SAI990323/Grounding4Rec#1]
Thanks for your great work.
I have a question: How are the movie_embedding and item_embedding generated? Do they come from one specific algorithm?

**Comment by SAI990323** [comment]
We utilized the straightforward approach of using LLaMA itself for extracting embeddings, without employing any specific techniques. While we acknowledge that there may exist numerous sophisticated methods to enhance performance, that is not the focal point of our discussion.

**Comment by zcfinal** [comment]
Thanks. I see.
